//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailReminderServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public int IssueTypeID { get; set; }
        public string Issue { get; set; }
        public string FromUserID { get; set; }
        public string ToUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public int TimeSlotID { get; set; }
        public int Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual IssueType IssueType { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
